kind: pipeline
type: docker
name: drone-test

clone:
  disable: true
steps:
  - name: clone
    image: alpine/git
    commands:
      - git config --global url."https://hub.fastgit.org".insteadOf https://github.com
      - git clone -b $DRONE_COMMIT_BRANCH $DRONE_GIT_SSH_URL .
  - name: build
    image: golang:1.17
    commands:
      - go env -w GO111MODULE=on
      - go env -w GOPROXY="https://goproxy.cn,direct"
      - go build -o main main.go

trigger:
  branch:
    - master
  event:
    - push
